# BACKEND: routes/tryOn.py
# ============================================================================

from fastapi import APIRouter, File, UploadFile, Form, HTTPException, Depends
from middleware.auth_middleware import get_current_user
import os
import uuid
import shutil
from datetime import datetime
from supabase import create_client, Client
from gradio_client import Client as GradioClient, handle_file

router = APIRouter()

supabase: Client = create_client(
    os.getenv("SUPABASE_URL"),
    os.getenv("SUPABASE_SERVICE_ROLE_KEY")
)

# List of free public spaces hosting IDM-VTON (Self-Healing List)
VTON_PROVIDERS = [
    "yisol/IDM-VTON",           # Official
    "Nymbo/Virtual-Try-On",     # Mirror 1
    "cuuupid/idm-vton",         # Mirror 2
    "zeroshot/idm-vton-sku"     # Mirror 3
]

@router.post("/generate")
async def generate_tryon(
    user_image: UploadFile = File(...),
    product_id: str = Form(...),
    current_user: dict = Depends(get_current_user)
):
    user_id = current_user["id"]
    temp_user_path = f"temp_user_{uuid.uuid4()}.jpg"

    try:
        # 1. Fetch Product
        product_response = supabase.table("products").select("*").eq("id", product_id).single().execute()
        if not product_response.data:
            raise HTTPException(status_code=404, detail="Product not found")
        
        product_image_url = product_response.data['image_url']
        
        # 2. Save User Image Locally
        with open(temp_user_path, "wb") as buffer:
            shutil.copyfileobj(user_image.file, buffer)
            
        # 3. Upload to Supabase (User History)
        with open(temp_user_path, "rb") as f:
            user_filename = f"{user_id}/{uuid.uuid4()}.jpg"
            supabase.storage.from_("user-photos").upload(
                user_filename, f.read(), {"content-type": "image/jpeg"}
            )
        user_photo_url = supabase.storage.from_("user-photos").get_public_url(user_filename)

        # 4. Try-On Logic with Fallback System
        generated_url = None
        last_error = None

        print(f"Starting VTON process for user {user_id}...")

        for provider in VTON_PROVIDERS:
            try:
                print(f"Attempting to connect to AI Provider: {provider}...")
                client = GradioClient(provider)
                
                print(f"Connected to {provider}. Sending job...")
                
                # IDM-VTON API Signature
                result_path = client.predict(
                    dict={"background": handle_file(temp_user_path), "layers": [], "composite": None},
                    garm_img=handle_file(product_image_url),
                    garment_des="clothing",
                    is_checked=True,
                    is_checked_crop=False,
                    denoise_steps=30,
                    seed=42,
                    api_name="/tryon"
                )
                
                # Handle tuple return (image, mask)
                final_image_path = result_path[0] if isinstance(result_path, (tuple, list)) else result_path
                
                print(f"Success! Image generated by {provider}")
                
                # 5. Upload Result
                generated_filename = f"{user_id}/{uuid.uuid4()}.jpg"
                with open(final_image_path, "rb") as f:
                    supabase.storage.from_("generated-images").upload(
                        generated_filename, f.read(), {"content-type": "image/jpeg"}
                    )
                generated_url = supabase.storage.from_("generated-images").get_public_url(generated_filename)
                break # Success!
                
            except Exception as e:
                print(f"Provider {provider} failed: {str(e)}")
                last_error = e
                continue # Try next provider

        if not generated_url:
            raise last_error or Exception("All AI services are currently unavailable.")

        # 6. Save to History
        supabase.table("tryon_history").insert({
            "user_id": user_id,
            "product_id": product_id,
            "original_image_url": user_photo_url,
            "generated_image_url": generated_url,
            "created_at": datetime.utcnow().isoformat()
        }).execute()

        return {
            "success": True,
            "original_image": user_photo_url,
            "generated_image": generated_url,
            "product_name": product_response.data["name"]
        }

    except Exception as e:
        print(f"Try-On Critical Error: {str(e)}")
        return {
            "success": False,
            "error": "AI Services busy, please try again later.",
            "original_image": user_photo_url if 'user_photo_url' in locals() else "",
            "generated_image": user_photo_url if 'user_photo_url' in locals() else "",
            "product_name": product_response.data["name"] if 'product_response' in locals() else ""
        }
        
    finally:
        if os.path.exists(temp_user_path):
            os.remove(temp_user_path)
